export const BURNLEY = {
  FLINDERS_STREET_LOOP: 1,
  FLINDERS_STREET_DIRECT: 2,
  SOUTHERN_CROSS: 3,
  FLAGSTAFF: 4,
  MELBOURNE_CENTRAL: 5,
  PARLIAMENT: 6,
  RICHMOND: 7,
  BURNLEY: 8,
  GLEN_WAVERLEY: 9,
  CAMBERWELL: 10,
  ALAMEIN: 11,
  RINGWOOD: 12,
  BELGRAVE: 13,
  LILYDALE: 14,
} as const;

export const CLIFTON_HILL = {
  FLINDERS_STREET_LOOP: 15,
  FLINDERS_STREET_DIRECT: 16,
  SOUTHERN_CROSS: 17,
  FLAGSTAFF: 18,
  MELBOURNE_CENTRAL: 19,
  PARLIAMENT: 20,
  JOLIMONT: 21,
  CLIFTON_HILL: 22,
  HURSTBRIDGE: 23,
  MERNDA: 24,
} as const;

export const DANDENONG = {
  FLINDERS_STREET_LOOP: 25,
  FLINDERS_STREET_DIRECT: 26,
  SOUTHERN_CROSS: 27,
  FLAGSTAFF: 28,
  MELBOURNE_CENTRAL: 29,
  PARLIAMENT: 30,
  RICHMOND: 31,
  SOUTH_YARRA: 32,
  CAULFIELD: 33,
  CLAYTON: 34,
  DANDENONG: 35,
  PAKENHAM: 36,
  EAST_PAKENHAM: 37,
  CRANBOURNE: 38,
} as const;

export const FLEMINGTON_RACECOURSE = {
  NEWMARKET: 39, // Reserved - currently unused.
  FLEMINGTON_RACECOURSE: 40, // Reserved - currently unused.
} as const;

export const FRANKSTON = {
  FLINDERS_STREET: 41,
  RICHMOND: 42,
  SOUTH_YARRA: 43,
  CAULFIELD: 44,
  FRANKSTON: 45,
} as const;

export const GIPPSLAND = {
  SOUTHERN_CROSS: 46,
  FLINDERS_STREET: 47,
  RICHMOND: 48,
  SOUTH_YARRA: 49,
  CAULFIELD: 50,
  CLAYTON: 51,
  DANDENONG: 52,
  PAKENHAM: 53,
  EAST_PAKENHAM: 54,
  BAIRNSDALE: 55,
} as const;

export const NEWPORT = {
  FLINDERS_STREET: 56,
  SOUTHERN_CROSS: 57,
  NORTH_MELBOURNE: 58,
  FOOTSCRAY: 59,
  NEWPORT: 60,
  WILLIAMSTOWN: 61,
  LAVERTON_LOOP: 62,
  LAVERTON_EXPRESS: 63,
  WERRIBEE: 64,
} as const;

export const NORTHERN = {
  FLINDERS_STREET_LOOP: 65,
  FLINDERS_STREET_DIRECT: 66,
  SOUTHERN_CROSS: 67,
  PARLIAMENT: 68,
  MELBOURNE_CENTRAL: 69,
  FLAGSTAFF: 70,
  NORTH_MELBOURNE: 71,
  UPFIELD: 72,
  NEWMARKET: 73, // Reserved - currently unused.
  BROADMEADOWS: 74,
  CRAIGIEBURN: 75,
  FOOTSCRAY: 76,
  SUNSHINE_JUNCTION: 77,
  SUNSHINE: 78,
  WATERGARDENS: 79,
  SUNBURY: 80,
} as const;

export const REGIONAL_WESTERN = {
  SOUTHERN_CROSS: 81,
  NORTH_MELBOURNE_JUNCTION: 82,
  NORTH_MELBOURNE_SEYMOUR: 83,
  NEWMARKET: 84, // Reserved - currently unused.
  BROADMEADOWS: 85,
  CRAIGIEBURN: 86,
  SEYMOUR: 87,
  ALBURY: 88,
  SHEPPARTON: 89,
  NORTH_MELBOURNE_RRL: 90,
  FOOTSCRAY: 91,
  SUNSHINE_JUNCTION: 92,
  SUNSHINE_BENDIGO: 93,
  WATERGARDENS: 94,
  SUNBURY: 95,
  BENDIGO: 96,
  ECHUCA: 97,
  SWAN_HILL: 98,
  SUNSHINE_DEER_PARK: 99,
  DEER_PARK: 100,
  BALLARAT: 101,
  MARYBOROUGH: 102,
  ARARAT: 103,
  WARRNAMBOOL: 104,
} as const;

export const SANDRINGHAM = {
  FLINDERS_STREET: 105,
  RICHMOND: 106,
  SOUTH_YARRA: 107,
  SANDRINGHAM: 108,
} as const;

export const STONY_POINT = {
  FRANKSTON: 109,
  STONY_POINT: 110,
} as const;
